# Generated by go2rpm 1
%bcond_without check

# https://github.com/aliyun/aliyun-openapi-meta
%global goipath         github.com/aliyun/aliyun-openapi-meta
%global commit          b64ab0cffa875183600b293ef7d0efd2304cadcf

%gometa

%global common_description %{expand:
Aliyun OpenAPI Meta Data.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Aliyun OpenAPI Meta Data

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Fri Nov 22 19:03:19 UTC 2019 Brandon Perkins <bdperkin@gmail.com> - 0-0.1.20191122gitb64ab0c
- Initial package

