# Generated by go2rpm 1
%bcond_without check

# https://github.com/aliyun/credentials-go
%global goipath         github.com/aliyun/credentials-go
%global commit          c03d72db93951189d986e275c4b9d3974674bbb1

%gometa

%global common_description %{expand:
Alibaba Cloud Credentials for Go.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md README-CN.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Alibaba Cloud Credentials for Go

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/alibabacloud-go/debug/debug)
BuildRequires:  golang(gopkg.in/ini.v1)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Fri Nov 22 16:07:30 UTC 2019 Brandon Perkins <bdperkin@gmail.com> - 0-0.1.20191122gitc03d72d
- Initial package

